services:
  bge-reranker:
    image: csdnai/bge-reranker-v2-m3:latest
    container_name: aiagent_reranker
    ports:
      - "8010:80"
    environment:
      MODEL_ID: BAAI/bge-reranker-v2-m3
      REVISION: main
    networks:
      - docker_default
    restart: unless-stopped

networks:
  docker_default:
    external: true
