import type { EnhancedToolDescription } from "./types";

export const TOOL_ENHANCED_DESCRIPTIONS: EnhancedToolDescription[] = [
  {
    name: "getStockHistory",
    description: "获取股票历史K线数据",
    whenToUse: "用户需要股票历史价格、K线数据、收盘价序列时。技术指标计算前通常需要先获取历史数据。",
    whenNotToUse: "用户需要实时行情时用getStockRealtime；需要财务数据时用getStockFinancial或getFinancialReport。",
    parameters: { code: { type: "string", description: "股票代码如sh.600036" }, startDate: { type: "string", description: "开始日期YYYY-MM-DD" } },
    exampleCalls: [{ description: "获取五粮液1年K线", parameters: { code: "sz.000858" } }],
    groupId: "market-data",
  },
  {
    name: "getStockRealtime",
    description: "获取股票实时行情快照",
    whenToUse: "用户需要当前最新价、涨跌幅、成交量等实时行情数据时。",
    whenNotToUse: "用户需要历史K线数据时用getStockHistory；需要财务数据时用getStockFinancial。",
    parameters: { code: { type: "string", description: "股票代码如600036" } },
    exampleCalls: [{ description: "获取招商银行实时行情", parameters: { code: "600036" } }],
    groupId: "market-data",
  },
  {
    name: "getStockFinancial",
    description: "获取股票财务数据（盈利能力指标）",
    whenToUse: "用户需要ROE、毛利率、净利率、营收、净利润等关键财务指标时。推荐efinance数据源。",
    whenNotToUse: "用户需要详细利润表/资产负债表/现金流量表数据时用getFinancialReport；需要估值指标时用hybridSearch查研报。",
    parameters: { code: { type: "string", description: "股票代码" } },
    exampleCalls: [{ description: "获取五粮液财报数据", parameters: { code: "000858" } }],
    groupId: "fundamental-data",
  },
  {
    name: "getFinancialReport",
    description: "获取股票详细财务报表（利润表/资产负债表/现金流量表）",
    whenToUse: "用户需要完整财务报表数据时，如'利润表'、'资产负债表'、'现金流量表'。已自动包含盈利能力指标，无需再调getStockFinancial。",
    whenNotToUse: "只需关键财务指标(ROE/毛利率)时用getStockFinancial更轻量；需要研报内容时用hybridSearch。",
    parameters: { code: { type: "string", description: "股票代码" }, report_type: { type: "string", description: "income/balance/cashflow" } },
    exampleCalls: [{ description: "获取五粮液利润表", parameters: { code: "000858", report_type: "income" } }],
    groupId: "fundamental-data",
  },
  {
    name: "calculateMA",
    description: "计算移动平均线",
    whenToUse: "用户需要MA指标时，如'MA5'、'均线'、'20日均线'。通常先调用getStockHistory获取数据。",
    whenNotToUse: "用户需要MACD时用calculateMACD；需要布林带时用calculateBollinger；需要综合技术分析时匹配technical-analysis Skill。",
    parameters: { period: { type: "number", description: "周期如5/10/20" } },
    exampleCalls: [{ description: "计算MA20", parameters: { period: 20 } }],
    groupId: "technical-analysis",
  },
  {
    name: "calculateMACD",
    description: "计算MACD指标",
    whenToUse: "用户需要MACD、DIF、DEA指标时。用于判断趋势方向和动量。",
    whenNotToUse: "用户只需要均线时用calculateMA；需要RSI时用calculateRSI。",
    parameters: { fast: { type: "number", description: "快线周期默认12" }, slow: { type: "number", description: "慢线周期默认26" } },
    exampleCalls: [{ description: "计算MACD", parameters: {} }],
    groupId: "technical-analysis",
  },
  {
    name: "calculateRSI",
    description: "计算RSI指标",
    whenToUse: "用户需要RSI、相对强弱指数时。判断超买超卖。",
    whenNotToUse: "用户需要波动率时用calculateVolatility；需要MACD时用calculateMACD。",
    parameters: { period: { type: "number", description: "周期默认14" } },
    exampleCalls: [{ description: "计算RSI14", parameters: { period: 14 } }],
    groupId: "technical-analysis",
  },
  {
    name: "calculateBollinger",
    description: "计算布林带指标",
    whenToUse: "用户需要布林带、BOLL指标时。判断价格波动区间和突破信号。",
    whenNotToUse: "用户需要均线时用calculateMA；需要KDJ时用calculateKDJ。",
    parameters: { period: { type: "number", description: "周期默认20" }, stdDev: { type: "number", description: "标准差倍数默认2" } },
    exampleCalls: [{ description: "计算布林带", parameters: {} }],
    groupId: "technical-analysis",
  },
  {
    name: "calculateKDJ",
    description: "计算KDJ指标",
    whenToUse: "用户需要KDJ、随机指标时。判断超买超卖和金叉死叉。",
    whenNotToUse: "用户需要RSI时用calculateRSI；需要MACD时用calculateMACD。",
    parameters: { period: { type: "number", description: "周期默认9" } },
    exampleCalls: [{ description: "计算KDJ", parameters: {} }],
    groupId: "technical-analysis",
  },
  {
    name: "calculateVWAP",
    description: "计算VWAP成交量加权平均价",
    whenToUse: "用户需要VWAP指标时。评估交易执行质量和机构成本基准。",
    whenNotToUse: "用户需要简单均线时用calculateMA；需要夏普比率时用calculateSharpeRatio。",
    parameters: {},
    exampleCalls: [{ description: "计算VWAP", parameters: {} }],
    groupId: "technical-analysis",
  },
  {
    name: "calculateSharpeRatio",
    description: "计算夏普比率",
    whenToUse: "用户需要评估风险调整后的收益、夏普比率时。衡量投资组合效率。",
    whenNotToUse: "用户需要波动率时用calculateVolatility；需要最大回撤时用calculateMaxDrawdown。",
    parameters: { riskFreeRate: { type: "number", description: "无风险利率默认0.03" } },
    exampleCalls: [{ description: "计算夏普比率", parameters: {} }],
    groupId: "technical-analysis",
  },
  {
    name: "calculateMaxDrawdown",
    description: "计算最大回撤",
    whenToUse: "用户需要最大回撤、最坏亏损幅度时。评估投资风险。",
    whenNotToUse: "用户需要VaR时用calculateVaR；需要波动率时用calculateVolatility。",
    parameters: {},
    exampleCalls: [{ description: "计算最大回撤", parameters: {} }],
    groupId: "technical-analysis",
  },
  {
    name: "calculateVolatility",
    description: "计算波动率",
    whenToUse: "用户需要波动率、年化波动率时。衡量价格波动程度。",
    whenNotToUse: "用户需要RSI时用calculateRSI；需要最大回撤时用calculateMaxDrawdown。",
    parameters: { annualize: { type: "boolean", description: "是否年化默认true" } },
    exampleCalls: [{ description: "计算年化波动率", parameters: {} }],
    groupId: "technical-analysis",
  },
  {
    name: "calculateCorrelation",
    description: "计算两个股票的相关系数",
    whenToUse: "用户需要两只股票的相关性、相关系数时。评估资产间联动关系。",
    whenNotToUse: "用户只需单只股票指标时用其他calculate*工具。",
    parameters: { code1: { type: "string", description: "第一只股票代码" }, code2: { type: "string", description: "第二只股票代码" } },
    exampleCalls: [{ description: "计算招商银行和五粮液相关性", parameters: { code1: "sh.600036", code2: "sz.000858" } }],
    groupId: "technical-analysis",
  },
  {
    name: "checkTradeCompliance",
    description: "A股交易合规检查",
    whenToUse: "用户需要检查交易是否符合A股规则（T+1、涨跌停、交易单位等）时。",
    whenNotToUse: "用户需要持仓限制检查时用checkPositionLimit；需要风险限额检查时用checkRiskLimits；需要VaR时用calculateVaR。",
    parameters: { code: { type: "string", description: "股票代码" }, direction: { type: "string", description: "buy/sell" } },
    exampleCalls: [{ description: "检查五粮液交易合规", parameters: { code: "000858", direction: "buy" } }],
    groupId: "risk-compliance",
  },
  {
    name: "checkPositionLimit",
    description: "持仓限制检查",
    whenToUse: "用户需要检查单只股票持仓是否超过总资产30%限制时。",
    whenNotToUse: "用户需要交易合规检查时用checkTradeCompliance；需要受限股票检查时用checkRestrictedStock。",
    parameters: { accountId: { type: "string", description: "账户ID" }, code: { type: "string", description: "股票代码" } },
    exampleCalls: [{ description: "检查持仓限制", parameters: { accountId: "default", code: "000858" } }],
    groupId: "risk-compliance",
  },
  {
    name: "checkRestrictedStock",
    description: "检查是否为受限股票",
    whenToUse: "用户需要检查股票是否处于限制交易状态（新股、退市整理期等）时。",
    whenNotToUse: "用户需要交易合规检查时用checkTradeCompliance；需要持仓限制时用checkPositionLimit。",
    parameters: { code: { type: "string", description: "股票代码" } },
    exampleCalls: [{ description: "检查受限股票", parameters: { code: "000858" } }],
    groupId: "risk-compliance",
  },
  {
    name: "calculateVaR",
    description: "计算风险价值VaR",
    whenToUse: "用户需要评估投资组合风险、计算VaR值时。衡量给定置信度下的最大可能损失。",
    whenNotToUse: "用户需要合规检查时用checkTradeCompliance；需要压力测试时用calculateStressTest。",
    parameters: { confidence: { type: "number", description: "置信度默认0.95" }, horizon: { type: "number", description: "持有期天数" } },
    exampleCalls: [{ description: "计算95%VaR", parameters: { confidence: 0.95, horizon: 1 } }],
    groupId: "risk-compliance",
  },
  {
    name: "calculateStressTest",
    description: "压力测试",
    whenToUse: "用户需要评估不同市场情景下的潜在损失时。模拟极端市场条件。",
    whenNotToUse: "用户需要VaR时用calculateVaR；需要风险限额检查时用checkRiskLimits。",
    parameters: { portfolio: { type: "object", description: "投资组合" }, scenarios: { type: "array", description: "压力情景" } },
    exampleCalls: [{ description: "压力测试", parameters: { portfolio: {}, scenarios: [] } }],
    groupId: "risk-compliance",
  },
  {
    name: "checkRiskLimits",
    description: "风险限额检查",
    whenToUse: "用户需要检查账户是否超过单日2%/单周5%/单月10%的风险限额时。",
    whenNotToUse: "用户需要VaR时用calculateVaR；需要合规检查时用checkTradeCompliance。",
    parameters: { accountId: { type: "string", description: "账户ID" } },
    exampleCalls: [{ description: "检查风险限额", parameters: { accountId: "default" } }],
    groupId: "risk-compliance",
  },
  {
    name: "hybridSearch",
    description: "RAG混合知识检索",
    whenToUse: "用户需要从知识库检索信息、查询研报内容、RAG问答时。",
    whenNotToUse: "用户需要股票行情数据时用getStockHistory；需要实时行情时用getStockRealtime；需要财务数据时用getStockFinancial。",
    parameters: { query: { type: "string", description: "检索查询" } },
    exampleCalls: [{ description: "检索五粮液研报", parameters: { query: "五粮液资产负债率" } }],
    groupId: "knowledge-documents",
  },
  {
    name: "placeOrder",
    description: "模拟下单",
    whenToUse: "用户需要在模拟账户中买入或卖出股票时。",
    whenNotToUse: "用户需要真实交易时此工具仅模拟；需要查看持仓时用getPositions；需要合规检查时先checkTradeCompliance。",
    parameters: { code: { type: "string", description: "股票代码" }, direction: { type: "string", description: "buy/sell" }, quantity: { type: "number", description: "数量" } },
    exampleCalls: [{ description: "买入100股五粮液", parameters: { code: "000858", direction: "buy", quantity: 100 } }],
    groupId: "paper-trading",
  },
  {
    name: "getPositions",
    description: "获取模拟持仓",
    whenToUse: "用户需要查看模拟账户的持仓情况时。",
    whenNotToUse: "用户需要下单时用placeOrder；需要账户总览时用getAccountSummary。",
    parameters: { accountId: { type: "string", description: "账户ID" } },
    exampleCalls: [{ description: "查看持仓", parameters: { accountId: "default" } }],
    groupId: "paper-trading",
  },
  {
    name: "getAccountSummary",
    description: "获取模拟账户总览",
    whenToUse: "用户需要查看模拟账户的总资产、盈亏、可用资金等汇总信息时。",
    whenNotToUse: "用户需要持仓明细时用getPositions；需要下单时用placeOrder。",
    parameters: { accountId: { type: "string", description: "账户ID" } },
    exampleCalls: [{ description: "账户总览", parameters: { accountId: "default" } }],
    groupId: "paper-trading",
  },
  {
    name: "getTradeHistory",
    description: "获取模拟交易记录",
    whenToUse: "用户需要查看模拟账户的历史交易记录时。",
    whenNotToUse: "用户需要当前持仓时用getPositions；需要下单时用placeOrder。",
    parameters: { accountId: { type: "string", description: "账户ID" } },
    exampleCalls: [{ description: "交易记录", parameters: { accountId: "default" } }],
    groupId: "paper-trading",
  },
  {
    name: "getValuationMetrics",
    description: "获取估值指标",
    whenToUse: "用户需要PE、PB、PS等估值指标时。评估股票是否被高估或低估。",
    whenNotToUse: "用户需要盈利能力指标(ROE/毛利率)时用getStockFinancial；需要详细报表时用getFinancialReport。",
    parameters: { code: { type: "string", description: "股票代码" } },
    exampleCalls: [{ description: "获取五粮液估值", parameters: { code: "000858" } }],
    groupId: "fundamental-data",
  },
  {
    name: "getDividendHistory",
    description: "获取分红历史",
    whenToUse: "用户需要股票分红派息历史数据时。评估分红收益率和分红持续性。",
    whenNotToUse: "用户需要财务报表数据时用getFinancialReport；需要估值指标时用getValuationMetrics。",
    parameters: { code: { type: "string", description: "股票代码" } },
    exampleCalls: [{ description: "获取五粮液分红历史", parameters: { code: "000858" } }],
    groupId: "fundamental-data",
  },
  {
    name: "getShareholderInfo",
    description: "获取股东信息",
    whenToUse: "用户需要股东结构、十大股东、股东人数等数据时。",
    whenNotToUse: "用户需要高管信息时用getExecutiveInfo；需要内幕交易数据时用getInsiderTrading。",
    parameters: { code: { type: "string", description: "股票代码" } },
    exampleCalls: [{ description: "获取五粮液股东信息", parameters: { code: "000858" } }],
    groupId: "fundamental-data",
  },
  {
    name: "getExecutiveInfo",
    description: "获取高管信息",
    whenToUse: "用户需要公司高管团队、薪酬、持股等信息时。",
    whenNotToUse: "用户需要股东信息时用getShareholderInfo；需要财务数据时用getStockFinancial。",
    parameters: { code: { type: "string", description: "股票代码" } },
    exampleCalls: [{ description: "获取五粮液高管信息", parameters: { code: "000858" } }],
    groupId: "fundamental-data",
  },
  {
    name: "getInsiderTrading",
    description: "获取内幕交易数据",
    whenToUse: "用户需要董监高增减持、内幕交易记录时。",
    whenNotToUse: "用户需要股东信息时用getShareholderInfo；需要合规检查时用checkTradeCompliance。",
    parameters: { code: { type: "string", description: "股票代码" } },
    exampleCalls: [{ description: "获取五粮液内幕交易", parameters: { code: "000858" } }],
    groupId: "fundamental-data",
  },
  {
    name: "getIndustryComparison",
    description: "获取行业对比数据",
    whenToUse: "用户需要同行业公司对比、行业排名数据时。",
    whenNotToUse: "用户只需要单公司数据时用getStockFinancial；需要研报时用hybridSearch。",
    parameters: { code: { type: "string", description: "股票代码" }, industry: { type: "string", description: "行业" } },
    exampleCalls: [{ description: "白酒行业对比", parameters: { code: "000858", industry: "白酒" } }],
    groupId: "fundamental-data",
  },
  {
    name: "parsePDF",
    description: "解析PDF文件",
    whenToUse: "用户上传PDF文件需要提取文本内容时。支持研报、财报PDF解析。",
    whenNotToUse: "用户需要分析图片时用analyzeImage；需要在线检索时用hybridSearch。",
    parameters: { filePath: { type: "string", description: "PDF文件路径" } },
    exampleCalls: [{ description: "解析研报PDF", parameters: { filePath: "/path/to/report.pdf" } }],
    groupId: "knowledge-documents",
  },
  {
    name: "analyzeImage",
    description: "分析图片内容（OCR或视觉理解）",
    whenToUse: "用户需要分析图片、截图、K线图表、财报图片时。自动选择PaddleOCR或视觉模型。",
    whenNotToUse: "用户需要解析PDF时用parsePDF；需要文本检索时用hybridSearch。",
    parameters: { image: { type: "string", description: "图片Base64编码" }, prompt: { type: "string", description: "可选分析提示" } },
    exampleCalls: [{ description: "分析K线图截图", parameters: { image: "base64...", prompt: "识别股票代码和趋势" } }],
    groupId: "knowledge-documents",
  },
];
